[[connection]]
database="fqdn\\databse"
id="username"
password="password"
port=""
RepeatInSeconds=10

    [[connection.metric]]
    name="name_of_metric"
    help="help for metric"
    statement="query returning an int"

[[connection]]
database="fqdn"
id="username"
password="password"
port="port_number"
RepeatInSeconds=10

    [[connection.metric]]
    name="name_of_metric"
    help="help for metric"
    statement="query returning an int"

    [[connection.metric]]
    name="name_of_metric"
    help="help for metric"
    statement="query returning an int"